vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: /uploads/article
            upload_destination: '%kernel.project_dir%/public/uploads/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
